apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: node-app
          image: montcarotte/jenkins_nodejs_app_demo:latest
          ports:
            - containerPort: 3000
          env:
            - name: APP_DB_HOST
              value: mysql-service
            - name: APP_DB_USER
              value: "admin"
        - name: mysql-server
          image: montcarotte/jenkins_nodejs_app_demo:mysql_latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "12345678" # the standard security practice for Kubernetes is to manage passwords through a separate secrets.yaml file. For the simplicity and demo purposes I am not doing it here.
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
